version: '3.8'
services:
  postgres:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
      

  pg-admin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT = 5050
    ports:
      - 5050:80

  redis:
    image: redis:7.0.7-alpine3.17
    container_name: redis_cache
    ports:
      - 6379:6379

      
  rust-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: rustserver-dc
    ports:
      - 10000:10000
    volumes:
      - './server:/usr/src/server'
      - '/usr/src/server/target'
    environment:
      - MY_LOG_LEVEL=info
      - MY_LOG_STYLE=Always
      - DATABASE_URL=${DATABASE_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISH_KEY=${STRIPE_PUBLISH_KEY}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - RESET_PASSWORD_SECRET=${RESET_PASSWORD_SECRET}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - postgres


    
      



  # surrealdb:
  #   image: surrealdb/surrealdb
  #   environment:
  #   - DB_USER=${DB_USER}
  #   - DB_PASS=${DB_PASS}
  #   ports:
  #   - 10001:8000
  #   volumes:
  #   - data:/var/lib/surrealdb/data
  #   command: "start --user ${DB_USER} --pass ${DB_PASS} --log full file://var/lib/postgresql/data"






volumes:
  data:
