services:
  - type: web
    name: rustserver-dc
    env: docker
    repo: https://github.com/arturs706/uwltoyshopserv.git
    region: frankfurt
    branch: main
    plan: free
    rootDir: server
    buildCommand: cargo build --release
    dockerCommand: ./server
    envVars: 
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: RESET_PASSWORD_SECRET
        generateValue: true



  - type: redis
    name: redis
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere
    region: frankfurt
    plan: free
databases:
  - name: postgres
    region: frankfurt
    plan: free



